Adds state with atom and initial timecontroller UI
electricitymaps/electricitymaps-contrib-rewrite pull request #21
Opened 2022-11-07 08:27 UTC by Kongkille

- Adds libraries
- atom logic
- change line width to 80
- Update api calls
- adds initial ui for timecontroller

## Issue

## Description

### Preview

2022-11-07 08:28 UTC, Kongkille commented on .prettierrc.js
> +  printWidth: 80,
I am having a lot of issues with 120 coding on my laptop

2022-11-07 08:43 UTC, Kongkille commented on web/src/utils/state/atomWithCustomStorage.ts
> +}
URL could likely be enabled on default, I don't see any case where you'd want session and localstorage together

.. Although it's a bit stupid to use this atom if you **only** use the url, then jotai has a built-in atom.

2022-11-07 11:56 UTC, madsnedergaard commented on .prettierrc.js
> +  printWidth: 80,
Can you try something inbetween first? Maybe 100?

Also this is fun 😄 
![Screenshot 2022-11-07 at 12 55 50](https://user-images.githubusercontent.com/3296643/200304301-25df8afa-3635-4aeb-a26c-c138ee61d473.png)

2022-11-07 12:00 UTC, madsnedergaard commented on .prettierrc.js
> +  printWidth: 80,
https://prettier.io/docs/en/options.html#print-width

2022-11-07 13:56 UTC, madsnedergaard reviewed
Some comments ❤️ 
(Sorry if it's a lot, but that's what you get when making large PRs 😛)

2022-11-07 13:56 UTC, madsnedergaard commented on web/src/utils/state/index.ts
> +  key: 'avg',
Can we give it a full name here instead, to make it nice and userfriendly? :)

2022-11-07 13:56 UTC, madsnedergaard commented on web/src/utils/state/atomWithCustomStorage.ts
> + * @see {@link https://github.com/pmndrs/jotai/blob/main/src/utils/atomWithStorage.ts}
This is cool! We should probably have started with just using one thing only and then added this functionality later on, but now it's here and it seems like it's working nicely :D

2022-11-07 13:56 UTC, madsnedergaard commented on web/src/utils/state/index.ts
> +import { atom } from 'jotai';
What is best practice with Jotai, should all atoms be defined here on a global level, or should some live next to the components/feature where it's used?

Take `timeAverageAtom` for instance, would it be better if it lives in `src/features/time/atoms.ts` or something like that?

2022-11-07 13:56 UTC, madsnedergaard commented on web/package.json
> +    "classnames": "^2.3.2",
Let's remove `classnames` as we're not using it and it's potentially leading to me abusing it 😅

2022-11-07 13:56 UTC, madsnedergaard commented on web/src/components/TimeAverageToggle.tsx
> +  };
Isn't eslint complaining about the abbreviation here? 🤔

2022-11-07 13:56 UTC, madsnedergaard commented on web/src/components/TimeAverageToggle.tsx
> +          <p className="w-15 h-6 text-gray-700 dark:text-gray-100">{text}</p>
Unrelated to this PR (but as a note to self/us), we should decide on which monochrome-scale we're using and be consistent (gray, zinc, slate, etc.). Maybe even force usage of only a specific type of possible?

2022-11-07 13:56 UTC, madsnedergaard commented on web/src/components/TimeSlider.tsx
> +import cx from 'classnames';
If we are to use a library like this, we should use https://www.npmjs.com/package/clsx

cc @tonypls, here's an example where it maybe makes sense to split classnames? Although the sorting-functionality should group those together anyway, so maybe it's not required...

2022-11-07 13:56 UTC, madsnedergaard commented on web/src/utils/state/atomWithCustomStorage.ts
> +}
We should probably document/make it clear somewhere when to use what - but we can also add that to a "let's document this"-list in Linear and do it later? :)

2022-11-07 14:53 UTC, Kongkille commented on web/src/utils/state/atomWithCustomStorage.ts
> +}
I can document it now, I think its better when it's fresh

2022-11-07 14:55 UTC, Kongkille commented on web/src/utils/state/atomWithCustomStorage.ts
> + * @see {@link https://github.com/pmndrs/jotai/blob/main/src/utils/atomWithStorage.ts}
Yeah this was way too complicated lol but at least I got to read through a lot of the jotai code :D

2022-11-07 14:55 UTC, Kongkille commented on web/src/utils/state/index.ts
> +  key: 'avg',
My thought process was that since it's in the URL we want to save that space as much as possible, especially as we start adding new flags?

2022-11-07 15:05 UTC, Kongkille commented on web/src/components/TimeAverageToggle.tsx
> +          <p className="w-15 h-6 text-gray-700 dark:text-gray-100">{text}</p>
Yes, I was thinking we could have Rasmus build a theme maybe?

2022-11-07 16:09 UTC, VIKTORVAV99 commented on web/src/utils/state/index.ts
> +  key: 'avg',
I pitched the idea to Mads on slack but I was thinking we could replicate the i18n behaviour for all URL keys. I.e., that it removes the key from the URL after it has updated the state (and local storage).

We would however need to add a share component based on `navigator.share()` that can compose URLs that has all parameters needed.

The benefit would be that the URLs are short and concise, but it would be an additional step to share the URL in a way that replicates the local state.

2022-11-07 16:22 UTC, VIKTORVAV99 reviewed
Just two small questions.

Mads got most of them already! 😅

2022-11-07 16:22 UTC, VIKTORVAV99 commented on web/src/components/TimeAverageToggle.tsx
> +}
Do we want to put all interfaces into an interface folder, like components, for easier reusability and code navigation?

2022-11-07 16:22 UTC, VIKTORVAV99 commented on web/src/utils/state/index.ts
> +export const isLeftPanelOpenAtom = atom<boolean>(false);
We might want to add session storage here, so this setting is persisted on page reloads. Should make any unexpected or accidental reload smoother as it doesn't reset the user view unexpectedly.

Local storage would be an option too if we want to persist it long term.

2022-11-07 20:44 UTC, madsnedergaard commented on web/src/utils/state/index.ts
> +import { atom } from 'jotai';
I think we can still have both, just like with types or components - there's general, cross-functionality (like your atom with multi storage) ones, and then some that are very specific to certain features. 
With that said I'm also okay with just grouping it all in one place now and then splitting out later if required :)

2022-11-08 12:15 UTC, Kongkille commented on web/src/utils/state/index.ts
> +export const isLeftPanelOpenAtom = atom<boolean>(false);
That's a great point, I was actually thinking of any cases where we'd want to use sessionstorage. I think that's a good example.

2022-11-08 12:17 UTC, Kongkille commented on web/src/components/TimeAverageToggle.tsx
> +}
Hmm I think it should be case dependant, in this case I think colocation makes sense because no other components would really care about this interface.

2022-11-08 12:27 UTC, Kongkille commented on web/src/utils/state/index.ts
> +  key: 'avg',
Ok I think for now we don't use abbreviations and then if it ends up becoming super long we can minimize it. It's just a key used in one place so we can always change it.

2022-11-08 14:05 UTC, Kongkille commented on web/src/components/TimeSlider.tsx
> +import cx from 'classnames';
Removed it for now

2022-11-08 14:05 UTC, Kongkille commented on web/src/utils/state/index.ts
> +import { atom } from 'jotai';
Roger that, let's take it on case by case then. I did not add anything in the docs about it

2022-11-08 14:32 UTC, Kongkille commented
Added functionality so that when you change the url parameter everything else updates as well

2022-11-08 14:48 UTC, VIKTORVAV99 commented on web/src/utils/state/index.ts
> +  key: 'avg',
My idea was that they would share the entire Url.

But if we take i18n as an example again:

if you visit `<url>?lang=en` i18n sets the language to English in the local state and then modify the URL to show just `<url>`.

Now we could do the same, the problem is when users need to share the specific state they are in they would have to use a share button that compose a URL like: `<url>?timeAverage=hour&solarLayer=true`. 

But the thing is we would have to do the share component anyway to share from the mobile apps.

2022-11-08 17:16 UTC, Kongkille commented on web/src/utils/state/index.ts
> +  key: 'avg',
My above message was probably not clear.

I understand the flow. My point is that from what I have seen people are less likely to use a 'Share' button versus simply copying the url and pasting it. For example, we have a tweet button which is very very rarely used. People are more likely to paste the url in their current browser and share that.

I therefore think trimming the URL might be a bad experience

2022-11-08 17:22 UTC, VIKTORVAV99 commented on web/src/utils/state/index.ts
> +  key: 'avg',
Ah yes, that's true.

We could evaluate this at a later date when we have a share component to facilitate the sharing from the mobile apps. However I don't think the URL parameters are a big issue so this should be a low priority item.

2022-11-08 17:24 UTC, Kongkille commented on web/src/utils/state/index.ts
> +  key: 'avg',
Yeah I mean it's also a bit about the aesthetics of the url which I am not sure what the value is. Personally I find it nice to be able to change state from the url and share it but perhaps there's some technical bias :D

2022-11-09 10:59 UTC, tonypls requested changes
I can update the naming if you like

2022-11-09 10:59 UTC, tonypls commented on web/src/utils/constants.ts
> +export enum TimeAverages {
I think time period is the right naming here, an average implies a mean value i.e. the average time to run a mile is 5 minutes. Here's more definitions of "time periods" https://www.britannica.com/dictionary/eb/3000-words/topic/periods-of-time

2022-11-09 11:44 UTC, madsnedergaard approved these changes
LGTM now :)

2022-11-09 11:52 UTC, tonypls approved these changes

2022-11-09 12:26 UTC, Kongkille commented on web/src/utils/constants.ts
> +export enum TimeAverages {
We asked platform who suggested time averages
https://electricitymaps.slack.com/archives/C01PWQYKX2R/p1666948439485229

2022-11-09 12:26 UTC, merged