mk/update timeslider
electricitymaps/electricitymaps-contrib-rewrite pull request #35
Opened 2022-11-15 16:50 UTC by Kongkille

- Style toggle group
- inject dependencies in toggle
- style and refactor timeslider
- Change header to be fixed positioned
- Remove error and loading handling on map. It should ideally always be drawn.
- Close left panel
- Add timeaxis
- refactor timecontroller
- add helpers
- remove magic number rule
- add clock icon in html file
- install react spinners
- change tailwind config. Should confirm best practice.
- add slider thumb custom icon

## Issue

## Description

### Preview

2022-11-15 16:57 UTC, Kongkille commented on web/src/features/time/TimeController.tsx
> +          (d) => dateToDatetimeIndex(d) === selectedDatetime
This is painful to look at but I don't really see another way of doing it other than constructing another datastructure for datetimes

2022-11-15 16:58 UTC, Kongkille commented on web/tailwind.config.js
> +      },
We should agree on some kind of standard for how we want to handle the brand colors

2022-11-15 17:18 UTC, VIKTORVAV99 reviewed
Just some idea's. 🙂

2022-11-15 17:18 UTC, VIKTORVAV99 commented on web/src/utils/formatting.ts
> +};
Just some nitpicks but I think this would look nicer as one combined switch statment with MW being the default.

2022-11-15 17:18 UTC, VIKTORVAV99 commented on web/src/utils/formatting.ts
> +    }
Maybe we should plan ahead here and calculates the range by using the different from the current datetime year and 2017?

That way it would automatically increment when a new year starts. (I assume we want to show as much long term data we possibly can.)

2022-11-15 17:18 UTC, VIKTORVAV99 commented on web/tailwind.config.js
> +      },
One option would be to create a theme and use CSS variables.
Should be easy enough to switch between light and darkmode that way as well.

2022-11-15 18:03 UTC, tonypls requested changes
Looks good, I'm keen to give it a good test but maybe after a couple of changes?

2022-11-16 08:30 UTC, Kongkille commented on web/src/features/time/TimeController.tsx
> +          (d) => dateToDatetimeIndex(d) === selectedDatetime
Haha yes, I actually thought of the exact same thing yesterday evening. I think a composite would be nicer to work with and I don't see any downsides

2022-11-16 08:35 UTC, Kongkille commented on web/src/utils/helpers.ts
> +export function dateToDatetimeIndex(date: Date) {
Hmm yes maybe, my thought is that we would still need to convert a JS date to a string somehow. 

This could be using the native ISO string method, but in the future we may want some other kind of string representation, this leaves us with a bit more flexibility

2022-11-16 08:47 UTC, Kongkille commented on web/src/features/time/TimeController.tsx
> +          (d) => dateToDatetimeIndex(d) === selectedDatetime
I've added an issue here, it needs to be done on the backend so I suggest we keep it separate from this PR since this works fine for now.

https://linear.app/electricitymaps/issue/ELE-1456/change-datetimes-object-to-contain-the-sorted-index

2022-11-16 08:54 UTC, Kongkille commented on web/src/utils/formatting.ts
> +    }
I think right now the idea is still that it would be 5 years regardless

2022-11-16 08:56 UTC, Kongkille commented on web/src/utils/formatting.ts
> +};
Hmm we don't really have any standards for when to use switch statements so I'd rather not spend the time ensuring same functionality with a refactor.

This was pulled from the other web project directly

2022-11-16 09:11 UTC, VIKTORVAV99 commented on web/src/utils/formatting.ts
> +};
I know it's just a early return mixed with a ternary operator look a little messy.

Multiple ifs would do the trick as well if you prefer that over a switch case.

2022-11-16 09:35 UTC, Kongkille commented on web/src/utils/formatting.ts
> +};
Roger that, I've removed the ternary operator :)

2022-11-16 09:37 UTC, madsnedergaard reviewed
Some comments, but it's so nice! <3

2022-11-16 09:38 UTC, madsnedergaard commented
![Screenshot 2022-11-16 at 10 38 04](https://user-images.githubusercontent.com/3296643/202144727-e95f670b-f195-47fe-b584-7d4fb0755f4f.png)

On hourly, dragging the slider all the way to the right results in this error

2022-11-16 09:40 UTC, VIKTORVAV99 commented on web/src/utils/formatting.ts
> +    }
This is just my own opinion, but 5 years feels a little "short" it's hard to see any long-term trends on just 5 years.

However, that discussion is not really part of this PR so let's drop it for now and we can discuss it separately later.

2022-11-16 09:41 UTC, madsnedergaard commented on web/src/features/time/TimeController.tsx
> +        'md: absolute bottom-0 w-full rounded-t-xl bg-white p-5 shadow-md dark:bg-gray-900 md:bottom-3 md:left-3 md:max-w-md md:rounded-xl'
There's a typo here, where should the `md:` belong to? 🤔

2022-11-16 10:12 UTC, Kongkille commented on web/src/features/time/TimeAxis.tsx
> +  const { ref, width } = useRefWidthHeightObserver(HORIZONTAL_MARGIN * 2);
Hmm well the thing is that those ticks are quite hard to render properly.

If we want to get rid of it we should perhaps switch to some other maintained library

I looked into mui base which can set up ticks but it was time consuming

https://mui.com/base/react-slider/#discrete-sliders

2022-11-16 10:13 UTC, Kongkille commented on web/src/utils/viewport.ts
> +export function useRefWidthHeightObserver(offsetX = 0, offsetY = 0) {
Adding the todo

2022-11-16 10:25 UTC, Kongkille commented
Ok I think all comments have been addressed

2022-11-16 10:54 UTC, madsnedergaard approved these changes
LGTM!

2022-11-16 11:58 UTC, merged